name: boost

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        a: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
        b: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
    steps:
      - name: Get VS Code CLI
        run: |
          curl -fsSL -o vscode.tar.gz "https://update.code.visualstudio.com/latest/linux-x64/stable"
          tar -xzf vscode.tar.gz
      - name: Install the extension
        run: ./VSCode-linux-x64/bin/code --install-extension vpp-lang.vplusplus --force
      - name: Verify
        run: ./VSCode-linux-x64/bin/code --list-extensions
